/** Hand-written one-line summary for each of the 78 unique sign pairings (canonical slug order). */
export const taglines: Record<string, string> = {
  "aries-and-aries": "Two sparks, one race — thrilling, competitive and never boring.",
  "aries-and-taurus": "Fire meets earth: fast meets steady, and each can teach the other.",
  "aries-and-gemini": "Playful, fast-moving and full of adventure — a lively, witty duo.",
  "aries-and-cancer": "Bold meets tender: protective passion that needs careful handling.",
  "aries-and-leo": "A blazing fire-sign match full of passion, praise and adventure.",
  "aries-and-virgo": "Action meets analysis — frustrating at first, surprisingly productive.",
  "aries-and-libra": "Opposites attract: the warrior and the diplomat complete each other.",
  "aries-and-scorpio": "Two Mars-ruled signs — magnetic, intense and occasionally explosive.",
  "aries-and-sagittarius": "Adventure partners for life — honest, spontaneous and fun.",
  "aries-and-capricorn": "Two cardinal leaders: ambition that either clashes or builds empires.",
  "aries-and-aquarius": "Rebels with a cause — independent, exciting and forward-looking.",
  "aries-and-pisces": "The warrior and the dreamer: tender protection meets gentle inspiration.",
  "taurus-and-taurus": "Double the loyalty, double the comfort — and double the stubbornness.",
  "taurus-and-gemini": "Steady meets restless: a curious pairing of roots and wings.",
  "taurus-and-cancer": "A cosy, devoted match built on security, comfort and care.",
  "taurus-and-leo": "Two fixed signs who love luxury and loyalty — and hate backing down.",
  "taurus-and-virgo": "Grounded, practical and quietly devoted — an earth-sign classic.",
  "taurus-and-libra": "Both ruled by Venus: a shared love of beauty at very different paces.",
  "taurus-and-scorpio": "Opposites with intense magnetism — deep loyalty and deeper passion.",
  "taurus-and-sagittarius": "Homebody meets explorer — a stretch that rewards patience.",
  "taurus-and-capricorn": "A rock-solid power couple built for the long haul.",
  "taurus-and-aquarius": "Tradition meets revolution: two fixed signs with different visions.",
  "taurus-and-pisces": "Gentle, romantic and soothing — the realist grounds the dreamer.",
  "gemini-and-gemini": "Endless conversation and fun — as long as someone pays the bills.",
  "gemini-and-cancer": "Head meets heart: wit and warmth learning each other's language.",
  "gemini-and-leo": "A sparkling, social duo that keeps life playful and bright.",
  "gemini-and-virgo": "Two Mercury minds — brilliant talkers with different priorities.",
  "gemini-and-libra": "An effortless air-sign match full of ideas, charm and conversation.",
  "gemini-and-scorpio": "Light meets depth — fascinating to each other, hard to pin down.",
  "gemini-and-sagittarius": "Opposites on the learning axis: curious, free and never bored.",
  "gemini-and-capricorn": "Spontaneity meets structure — a practical partnership with lessons.",
  "gemini-and-aquarius": "Intellectual soulmates — inventive, independent and endlessly curious.",
  "gemini-and-pisces": "Two mutable signs — imaginative and adaptable, but easily adrift.",
  "cancer-and-cancer": "Deep emotional understanding and a home full of love.",
  "cancer-and-leo": "Nurturer meets performer: warmth and devotion with tender egos.",
  "cancer-and-virgo": "Caring, loyal and supportive — a quietly strong partnership.",
  "cancer-and-libra": "Two cardinal signs seeking harmony in very different ways.",
  "cancer-and-scorpio": "An intensely emotional, loyal water-sign bond.",
  "cancer-and-sagittarius": "Home meets horizon — love that must balance roots and freedom.",
  "cancer-and-capricorn": "Opposites on the family axis: the nurturer and the provider.",
  "cancer-and-aquarius": "Emotion meets detachment — an unusual pair with much to learn.",
  "cancer-and-pisces": "A tender, intuitive and deeply romantic water-sign match.",
  "leo-and-leo": "Two suns in one sky — glamorous, generous and dramatic.",
  "leo-and-virgo": "The star and the stage manager: sparkle meets substance.",
  "leo-and-libra": "A charming, romantic duo who love beauty and a good social life.",
  "leo-and-scorpio": "Two fixed powerhouses — magnetic passion with a battle of wills.",
  "leo-and-sagittarius": "Warm, adventurous and fun — a fire-sign match made for joy.",
  "leo-and-capricorn": "Royalty meets authority: ambitious, status-savvy and proud.",
  "leo-and-aquarius": "Opposites on the self-and-others axis — heart meets vision.",
  "leo-and-pisces": "Grand romance meets dreamy devotion — sweet, but needs grounding.",
  "virgo-and-virgo": "Thoughtful, dependable and detail-perfect — but go easy on each other.",
  "virgo-and-libra": "Refined and considerate — practicality meets graceful diplomacy.",
  "virgo-and-scorpio": "Perceptive, loyal and private — a quietly powerful bond.",
  "virgo-and-sagittarius": "Details meet the big picture — two mutable signs learning balance.",
  "virgo-and-capricorn": "Practical, ambitious and loyal — an efficient earth-sign team.",
  "virgo-and-aquarius": "Two analytical minds — respect runs high, warmth takes work.",
  "virgo-and-pisces": "Opposites on the service axis: the healer and the helper.",
  "libra-and-libra": "Harmony, romance and good taste — if someone makes a decision.",
  "libra-and-scorpio": "Charm meets intensity — seductive, but trust needs building.",
  "libra-and-sagittarius": "A sociable, optimistic pair who love culture and adventure.",
  "libra-and-capricorn": "Two cardinal signs — elegant ambition with different priorities.",
  "libra-and-aquarius": "An air-sign match of ideals, friendship and fresh ideas.",
  "libra-and-pisces": "Romantic, gentle and idealistic — sweet, but needs a practical anchor.",
  "scorpio-and-scorpio": "Intense, loyal and all-consuming — soulmates or sworn rivals.",
  "scorpio-and-sagittarius": "Depth meets freedom — magnetic, but on very different wavelengths.",
  "scorpio-and-capricorn": "A powerful, loyal alliance with serious long-term potential.",
  "scorpio-and-aquarius": "Two fixed signs with strong convictions — fascinating and stubborn.",
  "scorpio-and-pisces": "A deeply intuitive, soulful water-sign connection.",
  "sagittarius-and-sagittarius": "Two free spirits chasing the horizon together.",
  "sagittarius-and-capricorn": "Optimism meets realism — a pairing of vision and discipline.",
  "sagittarius-and-aquarius": "Independent, idealistic and adventurous — true friends first.",
  "sagittarius-and-pisces": "Two Jupiter-touched dreamers — inspiring, but easily scattered.",
  "capricorn-and-capricorn": "Ambitious and dependable — a power couple that must remember to play.",
  "capricorn-and-aquarius": "Both linked to Saturn: tradition and innovation joining forces.",
  "capricorn-and-pisces": "The builder and the dreamer — structure that gives dreams a home.",
  "aquarius-and-aquarius": "Two originals — best friends, co-conspirators and idea machines.",
  "aquarius-and-pisces": "Visionary meets mystic — idealistic, unusual and imaginative.",
  "pisces-and-pisces": "Soulful, romantic and deeply empathetic — someone needs to steer.",
};
